version: '3.8'

services:
  nagios:
    image: jasonrivers/nagios:latest
    container_name: nagios
    ports:
      - "8085:80"
    volumes:
      - ~/nagios/etc:/opt/nagios/etc
      - ~/nagios/var:/opt/nagios/var
      - ~/nagios/log:/var/log/nagios
      - ~/nagios/libexec:/opt/nagios/libexec
      - ~/nagios/custom-plugins:/opt/Custom-Nagios-Plugins

